n = -15:15;
u = unitstep(n);
u1 = unitstep(n-10);
u2 = unitstep(n+3);
u3 = unitstep(n-5);
u4 = unitstep(n+2);
u5 = unitstep(n-7);
x = exp(n.*-2).*u-exp(n.*-2).*u1;
h1 = (2.^-n).*u2 -(2.^-n).*u3;
h2 = 0.3.^n.*u4-0.3.^n.*u5;
n1 = min(n)+min(n):max(n)+max(n);
cL = conv(h1,x);
cR = conv(x,h1);
subplot(161);
stem(n1,cL);
title("Commutative Right");
subplot(162);
stem(n1,cL);
title("Commutative Left");
n2 = min(n)+min(n)+min(n):max(n)+max(n)+max(n);
aL = conv(x,conv(h2,h1));
subplot(163);
stem(n2,aL);title("Associative Left");
aR = conv(conv(x,h1),h2);
subplot(164);
stem(n2,aR);
title("Associative RHS");
dR = conv(x,h2)+conv(x,h1);
dL = conv(x,h1+h2);
subplot(165);
stem(n1,dL);title("Distributive Left");
subplot(166);
stem(n1,dR);
title("Distributive Right");